name: SamplePlugin
api: [1.9.0]
version: 1.0
load: POSTWORLD
main: JrDevTeam\SamplePlugin\FileName
author: PocketMiners JR Dev Team
website: http://pocketminers.com

commands:
 test: //name of command ran
  description: "This is a test command" //ties to permission below
  usage: "/pocketminers"
  permission: sampleplugin.user //ties to permission below

 

permissions:      
 samplepluigin.user:
  description: "Gives access to User commands"
  default: true

