name: SamplePlugin
api: [1.9.0]
version: 1.0
load: POSTWORLD
main: JrDevTeam\SamplePlugin\FileName
author: PocketMiners JR Dev Team
website: http://pocketminers.com

commands:
 pocketminers:
  description: "This is a test command"
  usage: "/pocketminers"
  permission: sampleplugin.user
  
permissions:      
 samplepluigin.user:
  description: "Gives access to User commands"
  default: true

